### PR TITLE
Implement mappers

### PR DESCRIPTION
**Pull request by jamesdabbs**
This won't be ready to go until I've got a couple more mappers implemented, but I wanted to check and make sure the `cpu > memory > mapper > rom` chain of responsibilities seemed reasonable as they stand.

### CODE REVIEW

**Comment by jamesdabbs** [comment]
That makes sense. I was hesitant to go ahead and implement `prg` vs `chr` because I don't really understand when we'll be using which. Is there a particular feature requirement that can help drive me towards that implementation?

**Comment by kingcons** [comment]
@jamesdabbs Ah, sure! This specific branch in the PPU's `read_vram` function currently implements the NROM behavior: https://github.com/jamesdabbs/reason-sandbox/blob/master/src/Ppu.re#L68

The equivalent branch of `write_vram` should also be updated to go through the mapper. There may be other cases that I'm not thinking of, but accessing rom.chr is the main thing and I think those are th only two such situations in the codebase right now.

**Comment by jamesdabbs** [comment]
Ah, that helps, thanks. Does that last commit seem appropriate there?

**Comment by kingcons** [comment]
Yep, that looks like the right fix. :+1:

**Pull request closed without merging**
